# Generated by Django 2.2.6 on 2020-01-23 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile No.')),
                ('insurance_company', models.CharField(choices=[('Bupa', 'Bupa'), ('MedGulf', 'MedGulf'), ('MedNet', 'MedNet'), ('Tawnyia', 'Tawnyia'), ('Saudi Enaya', 'Saudi Enaya')], default='bupa', max_length=30, verbose_name='Insurance Company')),
                ('dipensing_date', models.DateField(verbose_name='Dispensing Date')),
                ('next_dispensing', models.DateField(verbose_name='Next Dispensing Date')),
                ('dispensing_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
