# Generated by Django 2.2.6 on 2020-01-21 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_code', models.CharField(max_length=6, verbose_name='Pharmacy Code')),
                ('pharmacy_name', models.CharField(max_length=50, verbose_name='Pharmacy Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_name', models.CharField(max_length=200, verbose_name='Pharmacist Name')),
                ('pharmacist_code', models.CharField(max_length=10, verbose_name='Employee Code')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_registeration.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile No.')),
                ('insurance_company', models.CharField(choices=[('Bupa', 'Bupa'), ('MedGulf', 'MedGulf'), ('MedNet', 'MedNet'), ('Tawnyia', 'Tawnyia'), ('Saudi Enaya', 'Saudi Enaya')], default='bupa', max_length=30, verbose_name='Insurance Company')),
                ('dipensing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dispensing Date')),
                ('next_dispensing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next Dispensing Date')),
                ('dispensing_pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guest_registeration.Pharmacist')),
                ('dispensing_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_registeration.Pharmacy')),
            ],
        ),
    ]
