# Generated by Django 3.0.5 on 2020-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chefs'},
        ),
        migrations.AlterModelOptions(
            name='whyyouchooseus',
            options={'verbose_name': 'why you choose us', 'verbose_name_plural': 'why you choose us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
